[2023-12-12T01:30:00.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_openaq.load_stations_data manual__2023-12-12T01:29:55.920201+00:00 [queued]>
[2023-12-12T01:30:00.560+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_openaq.load_stations_data manual__2023-12-12T01:29:55.920201+00:00 [queued]>
[2023-12-12T01:30:00.560+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-12T01:30:00.566+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-12-12 01:29:55.920201+00:00
[2023-12-12T01:30:00.570+0000] {standard_task_runner.py:57} INFO - Started process 219 to run task
[2023-12-12T01:30:00.573+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_openaq', 'load_stations_data', 'manual__2023-12-12T01:29:55.920201+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/dag_openaq.py', '--cfg-path', '/tmp/tmptykj4nnp']
[2023-12-12T01:30:00.576+0000] {standard_task_runner.py:85} INFO - Job 362: Subtask load_stations_data
[2023-12-12T01:30:00.610+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_openaq.load_stations_data manual__2023-12-12T01:29:55.920201+00:00 [running]> on host 2be5b1614f4e
[2023-12-12T01:30:00.664+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_openaq' AIRFLOW_CTX_TASK_ID='load_stations_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T01:29:55.920201+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-12T01:29:55.920201+00:00'
[2023-12-12T01:30:00.666+0000] {main.py:22} INFO - Archivo de configuracion leido correctamente.
[2023-12-12T01:30:00.666+0000] {utils.py:25} INFO - Obteniendo datos de https://api.openaq.org/v2/locations...
[2023-12-12T01:30:07.100+0000] {utils.py:39} ERROR - La peticion ha fallado. Codigo del error: 408 Client Error: Request Time-out for url: https://api.openaq.org/v2/locations?limit=2500
[2023-12-12T01:30:07.103+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/scripts/utils.py", line 29, in get_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 408 Client Error: Request Time-out for url: https://api.openaq.org/v2/locations?limit=2500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main.py", line 34, in load_locations
    json_api = get_data(base_url, endpoint, headers, params=params)
  File "/opt/airflow/scripts/utils.py", line 40, in get_data
    raise Exception(f"La peticion ha fallado. Codigo del error: {e}")
Exception: La peticion ha fallado. Codigo del error: 408 Client Error: Request Time-out for url: https://api.openaq.org/v2/locations?limit=2500
[2023-12-12T01:30:07.121+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_openaq, task_id=load_stations_data, execution_date=20231212T012955, start_date=20231212T013000, end_date=20231212T013007
[2023-12-12T01:30:07.130+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 362 for task load_stations_data (La peticion ha fallado. Codigo del error: 408 Client Error: Request Time-out for url: https://api.openaq.org/v2/locations?limit=2500; 219)
[2023-12-12T01:30:07.141+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T01:30:07.174+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
