[2023-12-12T01:22:15.955+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_openaq.create_stored_procedures manual__2023-12-12T01:22:14.274918+00:00 [queued]>
[2023-12-12T01:22:15.959+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_openaq.create_stored_procedures manual__2023-12-12T01:22:14.274918+00:00 [queued]>
[2023-12-12T01:22:15.959+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-12T01:22:15.964+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_stored_procedures> on 2023-12-12 01:22:14.274918+00:00
[2023-12-12T01:22:15.968+0000] {standard_task_runner.py:57} INFO - Started process 385 to run task
[2023-12-12T01:22:15.972+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_openaq', 'create_stored_procedures', 'manual__2023-12-12T01:22:14.274918+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/dag_openaq.py', '--cfg-path', '/tmp/tmpipk0mn7i']
[2023-12-12T01:22:15.974+0000] {standard_task_runner.py:85} INFO - Job 352: Subtask create_stored_procedures
[2023-12-12T01:22:16.019+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_openaq.create_stored_procedures manual__2023-12-12T01:22:14.274918+00:00 [running]> on host 63013c88d645
[2023-12-12T01:22:16.085+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_openaq' AIRFLOW_CTX_TASK_ID='create_stored_procedures' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T01:22:14.274918+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-12T01:22:14.274918+00:00'
[2023-12-12T01:22:16.086+0000] {sql.py:274} INFO - Executing: create or replace procedure pETL_load_dim_location()
language plpgsql
as $$
begin 
        -- merge changes to dim_location
        MERGE INTO dim_location
        USING stg_locations
        ON dim_location.id = stg_locations.id
        WHEN MATCHED THEN
            UPDATE SET
                id = stg_locations.id,
                city = stg_locations.city,
                name = stg_locations.name,
                country_code = stg_locations.country,
                sources = stg_locations.sources,
                ismobile = stg_locations.ismobile,
                isanalysis = stg_locations.isanalysis,
                sensortype = stg_locations.sensortype,
                coordinates_latitude = stg_locations.coordinates_latitude,
                coordinates_longitude = stg_locations.coordinates_longitude,
                updated_at = current_timestamp
        WHEN NOT MATCHED THEN
            INSERT (id, city, name, country_code, sources, ismobile, isanalysis, sensortype, 
                    coordinates_latitude, coordinates_longitude)
             VALUES (stg_locations.id, stg_locations.city, stg_locations.name, stg_locations.country, stg_locations.sources,
                    stg_locations.ismobile, stg_locations.isanalysis, stg_locations.sensortype, stg_locations.coordinates_latitude,
                    stg_locations.coordinates_longitude);
end;
$$

;
create or replace procedure pETL_update_country_dim_location()
language plpgsql
as $$
begin 
        -- update country name to dim location
        UPDATE dim_location
        SET country_name = stg_countries.name
        FROM stg_countries
        WHERE dim_location.country_code = stg_countries.code;
end;
$$

;
create or replace procedure pETL_load_dim_parameter()
language plpgsql
as $$
begin 
        -- merge changes to dim parameter
        MERGE INTO dim_parameter
        USING stg_parameters
        ON dim_parameter.id = stg_parameters.id
        WHEN MATCHED THEN
            UPDATE SET
                code = stg_parameters.name,
                displayName = stg_parameters.displayName,
                description = stg_parameters.description,
                preferredUnit = stg_parameters.preferredUnit,
                updated_at = current_timestamp
        WHEN NOT MATCHED THEN
            INSERT (id, code, displayName, description, preferredUnit)
            VALUES (stg_parameters.id, stg_parameters.name, stg_parameters.displayName, 
                    stg_parameters.description, stg_parameters.preferredUnit);
end;
$$

;
create or replace procedure pETL_load_fact_measure()
language plpgsql
as $$
begin 
         -- merge changes to fact_measure
        MERGE INTO fact_measure
        USING stg_measurements
        ON SHA1(stg_measurements.locationid + stg_measurements.parameter + stg_measurements.value + stg_measurements.date_utc)
            = SHA1(fact_measure.location_id + fact_measure.parameter_code + fact_measure.value + fact_measure.date_utc)
        WHEN MATCHED THEN
            UPDATE SET
                location_id = stg_measurements.locationid,
                parameter_code = stg_measurements.parameter,
                value = stg_measurements.value,
                date_local = stg_measurements.date_local,
                date_utc = stg_measurements.date_utc,
                updated_at = current_timestamp
        WHEN NOT MATCHED THEN
            INSERT (location_id, parameter_code, value, date_local, date_utc)
            VALUES (stg_measurements.locationid, stg_measurements.parameter, 
                stg_measurements.value, stg_measurements.date_local, stg_measurements.date_utc);
end;
$$
;
[2023-12-12T01:22:16.086+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-12-12T01:22:16.087+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2023-12-12T01:22:16.091+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2023-12-12T01:22:16.850+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "nicolasmvinciguerra_coderhouse" does not exist

[2023-12-12T01:22:16.879+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_openaq, task_id=create_stored_procedures, execution_date=20231212T012214, start_date=20231212T012215, end_date=20231212T012216
[2023-12-12T01:22:16.912+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 352 for task create_stored_procedures (connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "nicolasmvinciguerra_coderhouse" does not exist
; 385)
[2023-12-12T01:22:16.958+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T01:22:17.045+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
