[2023-12-12T01:37:42.062+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_openaq_dw_hourly_catchup.load_stations_data scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-12T01:37:42.084+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_openaq_dw_hourly_catchup.load_stations_data scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-12T01:37:42.086+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-12-12T01:37:42.129+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-12-05 00:00:00+00:00
[2023-12-12T01:37:42.156+0000] {standard_task_runner.py:57} INFO - Started process 895 to run task
[2023-12-12T01:37:42.171+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'update_openaq_dw_hourly_catchup', 'load_stations_data', 'scheduled__2023-12-05T00:00:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/dag_openaq_catchup.py', '--cfg-path', '/tmp/tmp39lt2_wk']
[2023-12-12T01:37:42.215+0000] {standard_task_runner.py:85} INFO - Job 405: Subtask load_stations_data
[2023-12-12T01:37:42.616+0000] {task_command.py:416} INFO - Running <TaskInstance: update_openaq_dw_hourly_catchup.load_stations_data scheduled__2023-12-05T00:00:00+00:00 [running]> on host 2be5b1614f4e
[2023-12-12T01:37:44.055+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_openaq_dw_hourly_catchup' AIRFLOW_CTX_TASK_ID='load_stations_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-05T00:00:00+00:00'
[2023-12-12T01:37:44.070+0000] {main.py:22} INFO - Archivo de configuracion leido correctamente.
[2023-12-12T01:37:44.071+0000] {utils.py:25} INFO - Obteniendo datos de https://api.openaq.org/v2/locations...
[2023-12-12T01:37:50.314+0000] {utils.py:73} INFO - Conexi√≥n a la base de datos establecida exitosamente.
[2023-12-12T01:37:52.755+0000] {utils.py:90} INFO - Cargando datos en la tabla stg_locations...
[2023-12-12T01:38:04.674+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-12T01:38:05.033+0000] {process_utils.py:131} INFO - Sending 15 to group 895. PIDs of all processes in the group: [895]
[2023-12-12T01:38:05.142+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 895
[2023-12-12T01:38:05.153+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-12T01:38:05.194+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py:736 UserWarning: DB-API extension cursor.connection used
